dev:
    - synth input port # linux qsynth
    - timidity port 0
    - loopmidi
    - loopbe
    - fluidsynth-midi
    - fluid-synth
    - bassmidi driver (port a)
    - microsoft midi mapper # lowest preference
    - zynaddsubfx
    - hexter
    - midi in
    - virtual raw midi # carla
    - midi through
    - virmidi
    - qjackctl

